Feature/layout: implemented desktop layout
petrovskya/Helyfly pull request #1
Opened 2023-03-01 11:25 UTC by petrovskya

1. feat: implemeted Helyfly desktop layout
2. Changes:
    - added layout to eight sections of the page;
    - added CSS styles to each section;
    - added global styles, variales & mixins for styles;
    - added readme file for the project;
3. How to test:
    - <a href="https://petrovskya.github.io/Helyfly/">View Demo</a>
    - <a href="https://www.figma.com/file/fMyOAiBkWJ4LtAacwdmIyB/testTask?node-id=0%3A1&t=vpEqZ4WXzU4tIKIF-0">View layout in Figma</a>

2023-03-02 11:00 UTC, irina-sinitsyna requested changes

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  color: #ffffff;
```suggestion
  color: #fff;
```

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +.header-banner__title {
please add empty lines between the groups of properties all over the project

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  padding: 20px 38px 20px;
```suggestion
  padding: 20px 38px;
```

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  border: 3px solid #ffffff;
please fix according to previous comments

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  font-weight: 900;
!

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  color: #ffffff;
same

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  padding-right: 113px;
please combine it in one line

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  font-weight: 400;
it's a default value, could we get rid of it?

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  font-weight: 400;
same, default value

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  color: #ffffff;
```suggestion
  color: #fff;
```

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  background-size: cover;
could be combined in one property

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  background-color: #ffffff;
!

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  list-style: none;
please fix properties order here and check all over styles

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  font-weight: 400;
default, could it be removed?

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  color: #ffffff;
!

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  padding: 140px 0 85px 0;
```suggestion
  padding: 140px 0 85px;
```

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  font-weight: 400;
please check it it's necessary

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  font-weight: 400;
!

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  font-weight: 400;
!

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  top: 0px;
please don't use px or any other units with 0

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  top: 0px;
!

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  font-weight: 400;
!

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  padding: 0px 66px 41px 66px;
!

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  padding: 0px 66px 41px 66px;
also it can be simplified

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  flex-direction: row;
default value, please remove

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  flex-direction: row;
!

2023-03-02 11:00 UTC, irina-komissarova commented on styles/styles.css
> +  padding: 3px 66px 31px 66px;
can be simplified as in previous comments

2023-03-02 11:00 UTC, irina-sinitsyna commented on styles/styles.css
> +  padding: 60px 0 50px 0;
simplify

2023-03-02 11:00 UTC, irina-sinitsyna commented on styles/styles.css
> +/*# sourceMappingURL=styles.css.map */
?

2023-03-02 13:23 UTC, petrovskya commented on styles/styles.css
> +  font-weight: 400;
The value from the layout for this element differs from the inherited
Screenshot  <![image](https://user-images.githubusercontent.com/105793821/222439966-5bf6c1a5-388e-465c-8b76-239db07aed08.png)>

2023-03-02 13:25 UTC, petrovskya commented on styles/styles.css
> +  font-weight: 400;
The value from the layout for this element differs from the inherited. 
![image](https://user-images.githubusercontent.com/105793821/222441070-6973a225-eaf3-42ae-8df9-4a7fcc184ca2.png)

2023-03-02 14:44 UTC, petrovskya commented on styles/styles.css
> +  font-weight: 400;
The value from the layout for this element differs from the inherited.

2023-03-03 08:04 UTC, irina-sinitsyna approved these changes

2023-03-03 08:04 UTC, merged